name: Build and Sign Lakyari APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_signed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Decode Keystore (from secret KEYSTORE_BASE64)
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ -z "$KEYSTORE_BASE64" ]; then echo "No keystore provided - skipping decode"; exit 0; fi
          echo "$KEYSTORE_BASE64" | base64 --decode > lakyari-release.keystore
      - name: Build Signed APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x ./gradlew || true
          ./gradlew assembleRelease --no-daemon || ./gradlew assembleDebug --no-daemon
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: Lakyari_v4_3_signed_apk
          path: app/build/outputs/apk/release/*.apk
